### ISSUE TITLE
Using wireguard iOs app

### ISSUE THREAD

**Issue by saturn-day** [patte/fly-tailscale-exit#2]

**Comment by patte** [comment]
what’s the issue?

**Comment by saturn-day** [comment]
I set up a wireguard-to-tailscale node on fly.io because I found the Tailscale iOS app to be unreliable (random disconnects, no autostart on boot). This can be achieved by running the tailscale app with 
`--advertise-routes=10.49.0.0/24`, where 10.49.0.0 is the wireguard subnet.

The routes have to manually be approved on tailscale.com. That was the original issue, and the fix.As a side note - I never managed to use a fly.io instance as a VPN end-point with wireguard alone.

Many thanks for the write-up, it put me in the right direction.
