### ISSUE TITLE
Fly.io no longer provides dedicated IPv4 addresses for free

### ISSUE THREAD

**Issue by huwan** [patte/fly-tailscale-exit#26]
I encountered the following warning while using `fly deploy`.

```
$ flyctl  deploy
...
==> Creating release
Error Services defined at indexes: 0 require a dedicated IP address. You currently have no dedicated IPs allocated. Please allocate at least one dedicated IP before deploying (`fly ips allocate-v4` and/or `fly ips allocate-v6`). Affected services:
  [0] udp/41641 => 8080

$ fly ips allocate-v4
? Looks like you're accessing a paid feature. Dedicated IPv4 addresses now costs $2/mo. Are you ok with this? 

```

After investigation, it was found that [Fly.io no longer provides dedicated IPv4 addresses for free](https://community.fly.io/t/announcement-shared-anycast-ipv4/9384). 

I wonder if there's a way to lift the restrictions mentioned above by modifying the tailscale configuration? Thank you for your help.

**Comment by gbraad** [comment]
You can assign a IPv6 address, as it doesn't really matter to the functionality.

**Comment by hoishing** [comment]
I face the similar problem, manually allocate a IPv6 with `fly ips allocate-v6` works for me

**Comment by huwan** [comment]
Thank you for the advice, it was very helpful.

**Comment by patte** [comment]
Thank you for bringing this up @huwan! I updated the readme to include those remarks: https://github.com/patte/fly-tailscale-exit/commit/e0a3772345c34679d8370e2ca31d72a685bbadc5
