### ISSUE TITLE
Instructions need to be updated to use V2 API (Machines)

### ISSUE THREAD

**Issue by gbraad** [patte/fly-tailscale-exit#29]
I have been keeping my own images and noticed that now the V2 API has become mandatory. I will update my instructions according to the following issue: https://github.com/spotsnel/tailscale-tailwings/issues/7. if you appreciate, I can port this back after I finished.

Currently dealing with some related issues with scaling, as `flyctl` has some unexpected behaviour: 

  * https://github.com/superfly/fly/issues/300
  * https://github.com/superfly/flyctl/issues/1990

**Comment by patte** [comment]
Dear @gbraad. Thank you very much for reporting. I updated the fly.toml and README in https://github.com/patte/fly-tailscale-exit/pull/30
May you confirm I covered everything?

**Comment by gbraad** [comment]
Looks OK. 👍
