### ISSUE TITLE
How come it seems to deploy 2 machines to tailscale?

### ISSUE THREAD

**Issue by CMCDragonkai** [patte/fly-tailscale-exit#34]
I followed the instructions and even set `flyctl scale count 1` and I see `fly-syd` and `fly-syd-1` in my tailscale admin. Why are there 2 machines? There's even only 1 app on fly dashboard. Is there a way to know which machine is actually connected?

**Comment by CMCDragonkai** [comment]
Also both are connected.

**Comment by RizwanNaasir** [comment]
<img width="871" alt="Screenshot 2023-09-22 at 9 36 59 AM" src="https://github.com/patte/fly-tailscale-exit/assets/97438351/b49f5b08-0836-4504-a729-4656eb69498c">

And yes there might be more than expected machines but you can always destroy them.

<img width="1218" alt="Screenshot 2023-09-22 at 9 38 06 AM" src="https://github.com/patte/fly-tailscale-exit/assets/97438351/fdd18863-be69-4e01-9fc6-7ef192ef7706">

**Comment by patte** [comment]
From the [README](https://github.com/patte/fly-tailscale-exit/blob/main/README.md#10-deploy-and-ip-and-scale):

> At the time of writing fly deploys two machines per default. For this setup you probably want 1 machine per region. Run the following to remove the second machine: `fly scale count 1`
