### ISSUE TITLE
Cannot use the exit node

### ISSUE THREAD

**Issue by CMCDragonkai** [patte/fly-tailscale-exit#35]
Is there a way to debug when after deploying everything and approving everything and then enabling:

```
sudo tailscale up --exit-node=fly-syd --exit-node-allow-lan-access=true
```

It's not possible to access the internet. All packets get dropped. `ping 8.8.8.8` doesn't work.

My tailscale network is up and running and I'm able to connect to other tailscale machines, but nothing gets routed over the exit node.

Furthermore I notice that the `fly-syd` doesn't respond to ICMP ping. I guess you have to use `tailscale ping fly-syd`, which does work, and the logs on the fly dashboard seem to indicate things are fine.

**Comment by CMCDragonkai** [comment]
Hmm I nuked my ACL and started again, this ended up making it work now.

**Comment by case** [comment]
@CMCDragonkai by "nuked my ACL" do you mean something in the Fly settings, or the Tailscale settings? (curious)

**Comment by CMCDragonkai** [comment]
Tailscale settings.
