### ISSUE TITLE
tailscale gets killed due to lack of memory

### ISSUE THREAD

**Issue by nmcc1212** [patte/fly-tailscale-exit#36]
After using the exit node for like a 30mins-1hr it always goes offline, and the log says 
```
Out of memory: Killed process 526 (tailscaled) total-vm:932140kB, anon-rss:185320kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:608kB oom_score_adj:0

```
 Is there a way to prevent this?

**Comment by patte** [comment]
I didn't yet encounter this.
You can of course just make the machine a little bigger: `fly scale memory 512 -a <app-name>`

**Comment by gbraad** [comment]
haven't seen this either. perhaps try a later version of Tailscale.
it might be related to what is being routed; so perhaps have a look at the traffic itself, as it seems the process starts to balloon.

**Comment by patte** [comment]
I mentioned it in the readme.
