### ISSUE TITLE
Update to new Fly template naming scheme

### ISSUE THREAD

**Issue by bslatyer** [patte/fly-tailscale-exit#5]
Hi @patte,

I've noticed that the new `flyctl` looks for Fly Templates now named `fly.toml` which causes the current `fly-template.toml` to not be found.

My suggestion would be to update all documentation and files to now refer to `fly.toml` instead of `fly-template.toml`

**Comment by bslatyer** [comment]
I can open a merge request if you want me to fix it?

**Comment by patte** [comment]
Sure you can. I’d love to review it.

**Comment by bslatyer** [comment]
No worries, I'll do it now.

**Comment by bslatyer** [comment]
Hey @patte

Still working on this.

**Comment by bslatyer** [comment]
Hey @patte,

It seems like Fly.io have deprecated the `fly-template.toml` naming and moved to `fly.toml`. My suggestions would be to inform users to change the `app-name=tailwings` to their own app created in Fly.io like `tailscale-bs` by using `flyctl create.` They would then use `flyctl deploy` to deploy their own app from the same folder once everything is ready.

This seems to work for me perfectly.

**Comment by patte** [comment]
done by: https://github.com/patte/fly-tailscale-exit/pull/17 and https://github.com/patte/fly-tailscale-exit/pull/19
